export interface BentoService {
  id: string;
  title: string;
  description: string;
  badge: string;
  iconName: "TrendingUp" | "Cpu" | "Layers" | "Activity" | "ShieldAlert";
  glowColor: "gold" | "cyan" | "magenta" | "default";
}

export interface MetricAchievement {
  id: string;
  value: number;
  decimals: number;
  prefix?: string;
  suffix?: string;
  label: string;
  description: string;
}

export interface RoadmapMilestone {
  id: string;
  phase: string;
  title: string;
  date: string;
  status: "completed" | "active" | "planned";
  description: string;
}

export interface FAQItem {
  id: string;
  category: "About Axiora" | "Signals & Membership" | "Payments & Security" | "Platform & Support";
  question: string;
  answer: string;
}

export const bentoServices: BentoService[] = [
  {
    id: "service-1",
    title: "Axiora Trading Interface",
    description: "A fast, clean workspace built to help you track market movements and analyze data in real time.",
    badge: "Fast Execution",
    iconName: "TrendingUp",
    glowColor: "default"
  },
  {
    id: "service-2",
    title: "AI Trading Signals",
    description: "Uses advanced artificial intelligence models to scan market trends and send you instant buy or sell signals.",
    badge: "AI Powered",
    iconName: "Cpu",
    glowColor: "default"
  },
  {
    id: "service-3",
    title: "Multi-Chain Tracker",
    description: "Easily monitor fund movements across different blockchains to spot hot tokens and new trends early.",
    badge: "Cross-Chain",
    iconName: "Layers",
    glowColor: "default"
  },
  {
    id: "service-4",
    title: "Real-Time Alert Feeds",
    description: "Get instant alerts for major wallet transfers and sudden price breakouts sent directly to your screen.",
    badge: "Live Streams",
    iconName: "Activity",
    glowColor: "default"
  },
  {
    id: "service-5",
    title: "Front-Running Shield",
    description: "Protects your larger trades from bot front-running and high slippage costs automatically.",
    badge: "Max Security",
    iconName: "ShieldAlert",
    glowColor: "default"
  }
];

export const metricsAchievements: MetricAchievement[] = [
  {
    id: "metric-1",
    value: 20,
    decimals: 0,
    suffix: "+",
    label: "Personal Clients",
    description: "Individual traders receiving one-on-one guidance and dedicated portfolio support."
  },
  {
    id: "metric-2",
    value: 3500,
    decimals: 0,
    suffix: "+",
    label: "Community Members",
    description: "Active members in our trading community sharing insights and market updates daily."
  },
  {
    id: "metric-3",
    value: 250,
    decimals: 0,
    suffix: "+",
    label: "VIP Members",
    description: "Premium tier members with exclusive access to advanced signals and priority support."
  },
  {
    id: "metric-4",
    value: 1,
    decimals: 0,
    prefix: "PKR ",
    suffix: " Million",
    label: "Generated in One Month",
    description: "Total earnings generated by our community within a single month of active trading."
  },
  {
    id: "metric-5",
    value: 7.8,
    decimals: 1,
    prefix: "Nearly PKR ",
    suffix: " Million",
    label: "Total Revenue",
    description: "Cumulative revenue generated across all programs and community initiatives to date."
  }
];

export const roadmapMilestones: RoadmapMilestone[] = [
  {
    id: "roadmap-1",
    phase: "Phase 1",
    title: "Foundation (2025)",
    date: "2025",
    status: "completed",
    description: "Established Axiora as a research-driven crypto trading community built on transparent analysis and consistent performance."
  },
  {
    id: "roadmap-2",
    phase: "Phase 2",
    title: "Community Expansion",
    date: "2025–2026",
    status: "completed",
    description: "Growing our member base across Telegram and digital channels with structured market updates and educational content."
  },
  {
    id: "roadmap-3",
    phase: "Phase 3",
    title: "Premium Membership",
    date: "2026",
    status: "active",
    description: "Launching tiered membership with priority signals, detailed trade setups, and exclusive community access."
  },
  {
    id: "roadmap-4",
    phase: "Phase 4",
    title: "Mobile App Launch",
    date: "2026",
    status: "planned",
    description: "Developing the official Axiora mobile application for on-the-go signal delivery and account management."
  },
  {
    id: "roadmap-5",
    phase: "Phase 5",
    title: "AI Features",
    date: "2027",
    status: "planned",
    description: "Integrating AI-assisted market analysis and smarter signal filtering into the Axiora platform."
  },
  {
    id: "roadmap-6",
    phase: "Phase 6",
    title: "Global Expansion",
    date: "2027+",
    status: "planned",
    description: "Scaling Axiora into a full crypto intelligence ecosystem with worldwide reach and expanded product offerings."
  }
];

export interface Testimonial {
  id: string;
  name: string;
  role: string;
  company: string;
  avatar: string;
  content: string;
  grade: string;
}

export const testimonials: Testimonial[] = [
  {
    id: "t-1",
    name: "Marcus T.",
    role: "Spot Trader",
    company: "Axiora Community",
    avatar: "MT",
    content: "Honestly, the signal quality is highly impressive. Took a BTC scalp setup yesterday and hit all take-profit targets smoothly.",
    grade: "PREMIUM"
  },
  {
    id: "t-2",
    name: "Priya K.",
    role: "Altcoin Trader",
    company: "Axiora Community",
    avatar: "PK",
    content: "I wasn't expecting much, but making a clean 113% ROI on my first altcoin signal completely blew me away. Excellent risk management.",
    grade: "MEMBER"
  },
  {
    id: "t-3",
    name: "James R.",
    role: "Community Member",
    company: "Telegram Group",
    avatar: "JR",
    content: "What I love about Axiora is they don't hide their losses. The transparency makes the winning streaks feel much more earned.",
    grade: "MEMBER"
  },
  {
    id: "t-4",
    name: "Elena M.",
    role: "Learning Trader",
    company: "Axiora Community",
    avatar: "EM",
    content: "The market breakdowns are so detailed. I'm actually learning how to read structure while taking their setups.",
    grade: "FREE TIER"
  },
  {
    id: "t-5",
    name: "Daniel W.",
    role: "Swing Trader",
    company: "Axiora Community",
    avatar: "DW",
    content: "Solid entries and clearly defined invalidation zones. This is exactly what a structured trading group should look like.",
    grade: "PREMIUM"
  },
  {
    id: "t-6",
    name: "Sofia L.",
    role: "Premium Member",
    company: "Axiora Community",
    avatar: "SL",
    content: "Joined the community last month. The win rate is very consistent, and the community updates keep me from panic-selling.",
    grade: "PREMIUM"
  },
  {
    id: "t-7",
    name: "Ahmed H.",
    role: "Futures Trader",
    company: "Axiora Community",
    avatar: "AH",
    content: "Very clear risk-to-reward parameters. The premium signals alone paid off my setup expenses within the first week.",
    grade: "PREMIUM"
  },
  {
    id: "t-8",
    name: "Connor B.",
    role: "Day Trader",
    company: "Axiora Community",
    avatar: "CB",
    content: "Impressive consistency. Even during choppy sideways markets, the team manages to spot high-probability scalp setups.",
    grade: "MEMBER"
  },
  {
    id: "t-9",
    name: "Rachel N.",
    role: "Independent Trader",
    company: "Axiora Community",
    avatar: "RN",
    content: "No exaggerated promises, just pure data and technical setups. It's a breath of fresh air in the crypto space.",
    grade: "MEMBER"
  },
  {
    id: "t-10",
    name: "Tyler J.",
    role: "ETH Trader",
    company: "Axiora Community",
    avatar: "TJ",
    content: "Hit an incredibly clean 80% gain on an ETH trade today. Highly recommend Axiora to anyone wanting data-backed entries.",
    grade: "PREMIUM"
  },
  {
    id: "t-11",
    name: "Naomi F.",
    role: "Technical Analyst",
    company: "Axiora Community",
    avatar: "NF",
    content: "The signals are highly accurate, but the market context they provide before an entry is the real value here.",
    grade: "PREMIUM"
  },
  {
    id: "t-12",
    name: "Chris P.",
    role: "Part-Time Trader",
    company: "Axiora Community",
    avatar: "CP",
    content: "Perfect for intermediate traders. Clear stop-losses mean I can take these signals with total peace of mind.",
    grade: "MEMBER"
  }
];

export const faqItems: FAQItem[] = [
  {
    id: "faq-1",
    category: "About Axiora",
    question: "What is Axiora?",
    answer: "Axiora is a crypto trading intelligence platform that provides research-based market analysis and trading signals for cryptocurrencies. Our goal is to help traders make informed decisions through professional market insights."
  },
  {
    id: "faq-2",
    category: "About Axiora",
    question: "When was Axiora established?",
    answer: "Axiora was originally launched in 2025 as a crypto trading community on Telegram. After building a growing community and serving hundreds of members, we are now expanding into a complete digital brand with a dedicated website and a future mobile application."
  },
  {
    id: "faq-3",
    category: "About Axiora",
    question: "How does Axiora work?",
    answer: "Our analysts continuously monitor the crypto market, identify potential trading opportunities, and share carefully researched trading signals with our community. Members simply receive the signals and execute the trades using their preferred exchange."
  },
  {
    id: "faq-4",
    category: "About Axiora",
    question: "Which cryptocurrencies do you cover?",
    answer: "We mainly provide analysis and trading signals for Bitcoin (BTC), Ethereum (ETH), and leading altcoins based on current market opportunities."
  },
  {
    id: "faq-5",
    category: "About Axiora",
    question: "What is Axiora's future vision?",
    answer: "Our roadmap includes expanding our community, launching the official Axiora mobile application, introducing additional premium tools, and building a complete crypto intelligence ecosystem."
  },
  {
    id: "faq-6",
    category: "Signals & Membership",
    question: "Do you offer free trading signals?",
    answer: "Yes. Free members receive a limited number of trading signals each week along with selected market updates."
  },
  {
    id: "faq-7",
    category: "Signals & Membership",
    question: "What do Premium members receive?",
    answer: "Premium members receive priority trading signals, more frequent market updates, detailed trade setups, and exclusive insights that are not available in the free community."
  },
  {
    id: "faq-8",
    category: "Signals & Membership",
    question: "How many signals are shared?",
    answer: "The exact number depends on market conditions. Premium members generally receive multiple high-quality signals throughout the week, while free members receive a limited selection."
  },
  {
    id: "faq-9",
    category: "Signals & Membership",
    question: "Are your signals guaranteed to be profitable?",
    answer: "No. Cryptocurrency markets are highly volatile, and no trading signal can guarantee profits. Every signal is based on research and analysis, but trading always involves risk."
  },
  {
    id: "faq-10",
    category: "Signals & Membership",
    question: "Which exchanges can I use?",
    answer: "You may execute our trading signals on any supported cryptocurrency exchange, including Binance, MEXC, Bitget, or any exchange that lists the recommended trading pairs."
  },
  {
    id: "faq-11",
    category: "Payments & Security",
    question: "Which payment methods do you accept?",
    answer: "Currently, subscription payments are accepted through supported cryptocurrencies."
  },
  {
    id: "faq-12",
    category: "Payments & Security",
    question: "Which cryptocurrencies can I use for payment?",
    answer: "We currently support payments using: Bitcoin (BTC), Ethereum (ETH), USDT (TRC-20), and USDT (ERC-20). Additional payment methods may be introduced in future updates."
  },
  {
    id: "faq-13",
    category: "Payments & Security",
    question: "Do I need to connect my crypto wallet?",
    answer: "No. At the moment, no wallet connection is required. Payments are simply transferred to our official wallet addresses."
  },
  {
    id: "faq-14",
    category: "Payments & Security",
    question: "Is my personal information secure?",
    answer: "Yes. We only collect the minimum information required to manage your membership and communicate with you. Your personal information is never shared with third parties without your consent."
  },
  {
    id: "faq-15",
    category: "Payments & Security",
    question: "Do you offer refunds?",
    answer: "Refund policies will be explained before subscription activation. Refund eligibility depends on the selected membership plan and applicable terms."
  },
  {
    id: "faq-16",
    category: "Platform & Support",
    question: "Is there an official Axiora mobile app?",
    answer: "Not yet. The Axiora mobile application is currently under development and will be launched in a future update."
  },
  {
    id: "faq-17",
    category: "Platform & Support",
    question: "Where will I receive trading signals?",
    answer: "Until the mobile application is launched, trading signals will be delivered through our official Telegram channels and other communication platforms announced by Axiora."
  },
  {
    id: "faq-18",
    category: "Platform & Support",
    question: "Can I access the website on mobile devices?",
    answer: "Yes. The Axiora website is fully responsive and optimized for mobile phones, tablets, laptops, and desktop computers."
  },
  {
    id: "faq-19",
    category: "Platform & Support",
    question: "How can I contact Axiora?",
    answer: "You can reach our team through Email: elitetrackers.offical@gmail.com or Telegram: @Corisher_asthato. Additional contact methods will be introduced in future updates."
  },
  {
    id: "faq-20",
    category: "Platform & Support",
    question: "Why should I choose Axiora?",
    answer: "Axiora focuses on quality over quantity. Our objective is to provide research-driven market analysis, transparent communication, and a professional trading experience while continuously expanding our products and services for the crypto community."
  }
];
